### PR TITLE
Perma & Brig

### PR DESCRIPTION
**Pull request by Pepsilawn**
this is how it looks i think at least at the time i write this i dont know can we just get mapdiffbot to generate previews
help

help2

why tihs is good for the game

### CODE REVIEW

**Comment by Pepsilawn** [comment]
draft cuz i need to fix what helian said i should fix @ perma

**Comment by Pepsilawn** [comment]
wrong button

**Comment by SgtHunk** [comment]
lol

**Comment by SgtHunk** [comment]
also i could install mapdiffbot but it won't work because it only previews the bottom z-level :/ so it'll be useless unless we split the .dmm into two

**Comment by Pepsilawn** [comment]
kilo2
kilo3

@SgtHunk

**Comment by SgtHunk** [comment]
cool idc

**Comment by SgtHunk** [comment]
merge conflicts btw

**Comment by Pepsilawn** [comment]
name 1 conflict

**Comment by Pepsilawn** [comment]
ok *pretends to care

**Comment by Pepsilawn** [comment]
github is stupid check this out

**Pull request closed without merging**
